### ISSUE TITLE
Some Links showing error

### ISSUE THREAD

**Issue by hello802** [manga-py/manga-py#334] opened 2020-09-10 18:54 UTC
# Bug report
i don't know why but some hiperdex links shwing this error.

link:-https://hiperdex.com/manga/excuse-me-this-is-my-room-english/

(base) PS C:\Users\Dev> manga-py https://hiperdex.com/manga/excuse-me-this-is-my-room-english/
Traceback (most recent call last):
  File "c:\users\Dev\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\Dev\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\Dev\Anaconda3\Script...
         -> <code object <module> at 0x000001ED13E5D660, file "C:\Users\Dev\Anaconda3\Scripts\manga-py.exe\__main__.py", line 2>
  File "C:\Users\Dev\Anaconda3\Scripts\manga-py.exe\__main__.py", line 7, in <module>
    sys.exit(main())
    |        -> <function main at 0x000001ED175FF0D8>
    -> <module 'sys' (built-in)>
  File "c:\users\Dev\anaconda3\lib\site-packages\manga_py\util.py", line 112, in main
    exit(run_util(args))
    |    |        -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    |    -> <function run_util at 0x000001ED175FCF78>
    -> <built-in function exit>
  File "c:\users\Dev\anaconda3\lib\site-packages\manga_py\util.py", line 83, in run_util
    _info = _run_util(args)
            |         -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            -> <function _run_util at 0x000001ED175FCE58>
  File "c:\users\Dev\anaconda3\lib\site-packages\manga_py\util.py", line 41, in _run_util
    Cli(args, _info).start()
    |   |     -> <manga_py.info.Info object at 0x000001ED17605208>
    |   -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    -> <class 'manga_py.cli.Cli'>
  File "c:\users\Dev\anaconda3\lib\site-packages\manga_py\cli\__init__.py", line 47, in start
    self.parser.start()
    -> <manga_py.cli.Cli object at 0x000001ED176050C8>
  File "c:\users\Dev\anaconda3\lib\site-packages\manga_py\parser.py", line 63, in start
    self.provider.process(self.params['url'], self.params)
    |                     |                   -> <manga_py.parser.Parser object at 0x000001ED17605548>
    |                     -> <manga_py.parser.Parser object at 0x000001ED17605548>
    -> <manga_py.parser.Parser object at 0x000001ED17605548>
  File "c:\users\Dev\anaconda3\lib\site-packages\manga_py\provider.py", line 111, in process
    self.loop_chapters()
    -> <manga_py.providers.hiperdex_com.HiperDexCom object at 0x000001ED17605788>
  File "c:\users\Dev\anaconda3\lib\site-packages\manga_py\provider.py", line 139, in loop_chapters
    if idx < _min or (count >= _max > 0) or self._check_archive():
  File "c:\users\Dev\anaconda3\lib\site-packages\manga_py\provider.py", line 115, in _check_archive
    _path = '%s.%s' % self.get_archive_path()
                      -> <manga_py.providers.hiperdex_com.HiperDexCom object at 0x000001ED17605788>
  File "c:\users\Dev\anaconda3\lib\site-packages\manga_py\provider.py", line 203, in get_archive_path
    _path = remove_file_query_params(self.get_archive_name())
            |                        -> <manga_py.providers.hiperdex_com.HiperDexCom object at 0x000001ED17605788>
            -> <function remove_file_query_params at 0x000001ED166C6EE8>
  File "c:\users\Dev\anaconda3\lib\site-packages\manga_py\base_classes\arc_name.py", line 12, in get_archive_name
    idx = self.get_chapter_index()
          -> <manga_py.providers.hiperdex_com.HiperDexCom object at 0x000001ED17605788>
  File "c:\users\Dev\anaconda3\lib\site-packages\manga_py\providers\rawdevart_com_old.py", line 11, in get_chapter_index
    return '-'.join(idx.group(1).split('.'))
                    -> None
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by gromenauer** [comment] 2020-09-11 08:56
Confirmed bug :bug: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.5 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.21
URL | `https://hiperdex.com/manga/excuse-me-this-is-my-room-english/`
 
``` sh
docker run \
  --interactive --tty --rm --name manga-py \
  -v $PWD:/home/manga/Manga --entrypoint manga-py \
  mangadl/manga-py \
    --destination /home/manga/Manga --cbz --zero-fill \
    --rename-pages --no-webp --show-current-chapter-info \
    https://hiperdex.com/manga/excuse-me-this-is-my-room-english/

```

``` py
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 11, in <module>
    load_entry_point('manga-py==1.21', 'console_scripts', 'manga-py')()
    └ <function load_entry_point at 0x7fd8ed0069d8>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 112, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7fd8e75d7840>
    └ <built-in function exit>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7fd8e75d7730>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7fd8e75d9ac8>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7fd8e75d9a90>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/parser.py", line 63, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7fd8e75d9b00>
    │                     └ <manga_py.parser.Parser object at 0x7fd8e75d9b00>
    └ <manga_py.parser.Parser object at 0x7fd8e75d9b00>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/provider.py", line 111, in process
    self.loop_chapters()
    └ <manga_py.providers.hiperdex_com.HiperDexCom object at 0x7fd8e75d9b70>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/provider.py", line 139, in loop_chapters
    if idx < _min or (count >= _max > 0) or self._check_archive():
  File "/usr/local/lib/python3.6/dist-packages/manga_py/provider.py", line 115, in _check_archive
    _path = '%s.%s' % self.get_archive_path()
                      └ <manga_py.providers.hiperdex_com.HiperDexCom object at 0x7fd8e75d9b70>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/provider.py", line 203, in get_archive_path
    _path = remove_file_query_params(self.get_archive_name())
            │                        └ <manga_py.providers.hiperdex_com.HiperDexCom object at 0x7fd8e75d9b70>
            └ <function remove_file_query_params at 0x7fd8ecadca60>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/base_classes/arc_name.py", line 12, in get_archive_name
    idx = self.get_chapter_index()
          └ <manga_py.providers.hiperdex_com.HiperDexCom object at 0x7fd8e75d9b70>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/providers/rawdevart_com_old.py", line 11, in get_chapter_index
    return '-'.join(idx.group(1).split('.'))
                    └ None
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by hello802** [comment] 2020-09-15 11:29
Did this bug fixed

**Comment by 1271** [comment] 2020-09-15 13:22
No, it will be fixed when there is free time. Thank you for understanding

**Comment by gromenauer** [comment] 2020-09-15 16:21
@hello802 the workaround is try to find it elsewhere and use one of the 200+ sites listed in https://manga-py.com/ as backup source

**Comment by 1271** [comment] 2020-09-20 10:03
@hello802 
Sorry to wait. Unfortunately, now I have some problems in my family. I will definitely come back as soon as I solve some of them.
Thank you for understanding

As @gromenauer  already wrote, you can use alternative projects. I'm really sorry that this delay happened

**Comment by 1271** [comment] 2020-10-03 09:08
Fixed. Please, check version 1.22

Sorry for long time a wait

**Comment by gromenauer** [comment] 2020-10-03 16:30
Works for me :+1: .
@hello802 have you tried? It's OK to close the bug for you?
 
Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.5 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.22
URL | `https://hiperdex.com/manga/excuse-me-this-is-my-room-english/`

**Comment by 1271** [comment] 2020-10-23 07:10
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py

**Closed as completed** 2020-10-23 07:13 UTC
Labels: bug
