### ISSUE TITLE
Getting a error while downloading from ac.qq "Error processing file: vol_00x"

### ISSUE THREAD

**Issue by omdev420** [manga-py/manga-py#301] opened 2020-05-10 14:20 UTC
Hey dev,
I am having an issue using manga-py, I received this error thrown:-

"E:\manga_py\provider.py:152:2020-05-10 19:45:40,128:Error processing file: vol_001"

Whenever i try to download with this arguments:-

manga-py https://ac.qq.com/Comic/comicInfo/id/644515

and I don't have a disk drive named E:
Funny

**Comment by 1271** [comment] 2020-05-10 18:35
Not sure I'll fix it.
Most likely, support will be removed for a while.

**Comment by gromenauer** [comment] 2020-05-11 08:12
E: Its not a Windows unit is a log Error (W: → Warning; I: → Info)

**Comment by gromenauer** [comment] 2020-05-11 08:14
Confirmed in docker

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.5
URL | `https://ac.qq.com/Comic/comicInfo/id/644515`
          
~~~ bash
docker run --interactive --tty --rm --name manga-py -v $PWD:/home/manga/Manga mangadl/manga-py manga-py --destination /home/manga/Manga --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info https://ac.qq.com/Comic/comicInfo/id/644515
~~~
~~~
Current chapter url: https://ac.qq.com/ComicView/index/id/644515/cid/1

"E:/manga_py/provider.py:152:2020-05-11 08:13:13,474:Error processing file: vol_001-0"
...
~~~

**Comment by 1271** [comment] 2020-05-11 08:29
> E: Its not a Windows unit is a log Error (W: → Warning; I: → Info)

Yeah... On small monitors, the word warning took up too much space, so I shortened it.
But since this causes confusion, I will return the full names of the messages. (already in git, will be in the next release)

**Comment by 1271** [comment] 2020-07-29 23:57
Done. Check for updates in pip version.
Sorry for that long 😅

**Comment by gromenauer** [comment] 2020-07-30 19:53
Works for me :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.4 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.20.2
URL | `https://ac.qq.com/Comic/comicInfo/id/644515`

**Comment by 1271** [comment] 2020-10-03 09:04
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py

**Closed as completed** 2020-12-17 07:09 UTC
Labels: bug
